global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'ux_server'
    static_configs:
      - targets: ['10.243.171.71:8080'] # Replace with the actual IP and port of your UX server.

  - job_name: 'satellites'
    static_configs:
      - targets: ['10.243.32.249:8080'] # Replace with the actual IPs and ports of your satellites.
